server {
    listen 80;
    root /usr/share/nginx/html;

    location /vibe-2026/ {
        try_files $uri $uri/ $uri.html =404;
    }

    location = /vibe-2026 {
        return 301 /vibe-2026/;
    }

    location = / {
        return 301 /vibe-2026/;
    }
}
